In [10]:
import pandas as pd
from sqlalchemy import create_engine, Column, Integer, String, Date, Text, text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# Configuração do PostgreSQL no Docker
DB_USER = "admin"
DB_PASSWORD = "admin123"
DB_HOST = "localhost"  # Se estiver rodando no Docker, use "localhost" ou o nome do serviço no docker-compose
DB_PORT = "5432"
DB_NAME = "mydatabase"

DATABASE_URL = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

# Criando a engine do SQLAlchemy
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

create_view_query = """
CREATE OR REPLACE VIEW testdois AS
SELECT * FROM nps_feedback;
"""
# Executar a query no banco
with engine.connect() as conn:
    conn.execute(text(create_view_query))
    conn.commit()  # Confirma a alteração
    print("View criada/atualizada com sucesso!")

View criada/atualizada com sucesso!

/tmp/ipykernel_27043/1479054260.py:18: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [5]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

# Configuração do PostgreSQL no Docker
DB_USER = "admin"
DB_PASSWORD = "admin123"
DB_HOST = "localhost"  # Se estiver rodando no Docker, use "localhost" ou o nome do serviço no docker-compose
DB_PORT = "5432"
DB_NAME = "mydatabase"

DATABASE_URL = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

# Criando a engine do SQLAlchemy
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

/tmp/ipykernel_27043/2024862198.py:18: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [6]:
query = "SELECT * FROM nps_feedback;"  # Nome da view
df = pd.read_sql(query, engine)
df

,id,nome,email,idade,genero,cidade,pais,categoria_nps,comentario_produto,comentario_atendimento,comentario_preco,comentario_entrega,comentario_geral,data_resposta
0,1,Kyle Odom,danaperkins@example.net,56,Feminino,Johnsonchester,Saint Pierre and Miquelon,Neutro,Exist value team lose school herself president.,Line provide market thing threat thus.,Production role present bad bad development.,Modern factor professor own staff month.,Cup trip soldier human our always evidence qua...,2025-02-10
1,2,Mr. Robert Sanchez PhD,hollycook@example.org,55,Feminino,Markburgh,United Kingdom,Neutro,Happen room project where.,Admit center foreign only despite people.,For trial event case call.,Service parent many resource budget consumer.,Enough best practice recognize consumer appear...,2025-02-10
2,3,Kayla Williams DDS,smithkatherine@example.org,45,Masculino,Scottview,Sierra Leone,Detrator,Important occur catch oil huge.,All community minute hard computer discussion.,Family real network capital.,General first time statement guess.,Start cause operation particularly itself resp...,2025-02-10
3,4,Kathleen Taylor,martinanthony@example.org,32,Feminino,Karenstad,Madagascar,Neutro,Rest own play try.,Bit score service pay individual agree dream.,Major floor his food hit.,Wife be look same win onto air.,Magazine others peace help.,2025-02-10
4,5,Cassandra Gomez,carrillodavid@example.com,46,Feminino,West Courtneychester,United Kingdom,Promotor,Upon top successful risk myself.,Field word spring western through least stop.,Gun discussion east voice determine like.,Of kind those southern whose information.,Decision agency hospital.,2025-02-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Sherry Harrison,jrobinson@example.com,31,Feminino,Beckyside,Canada,Neutro,Wish available break spend teacher glass deep ...,Chance bar writer college game exist make their.,Along protect name environment minute certain.,Conference generation almost house.,Network clear husband idea receive relationshi...,2025-02-10
96,97,Troy Washington,reyestina@example.net,61,Feminino,Maryview,Togo,Detrator,Agreement these project full everything wester...,Without stuff camera large drop rather professor.,Commercial certain word second.,Pattern risk accept mission child.,Blood beautiful lay property first need care.,2025-02-10
97,98,Laura Roman,brian99@example.org,37,Masculino,Carrieburgh,Barbados,Promotor,Top he box agreement.,Anyone what administration season guy himself ...,Heavy section actually use charge avoid.,Few most minute play determine.,Sound maintain every of push back.,2025-02-10
98,99,Kathryn Hunter,xmiller@example.org,57,Masculino,Baileyberg,Congo,Promotor,Remember yard understand enough adult return o...,Seven according including camera office of stage.,Between gas another ball rather.,Already check letter entire radio property mys...,Inside discover tell control along set side av...,2025-02-10
99,100,Herbert Chapman,juan64@example.com,57,Masculino,Lake Catherinestad,Ecuador,Detrator,Officer now capital pressure.,Enter bag within brother design wrong large.,Less hold clearly industry table lay and.,Pattern cut left especially.,Nice try produce.,2025-02-10