In [ ]:
import pandas as pd
import numpy as np
from faker import Faker

# Inicializar Faker para gerar dados fictícios
fake = Faker()

# Definir número de linhas
num_rows = 1000

# Gerar dados fictícios
data = {
    "Nome": [fake.name() for _ in range(num_rows)],
    "Email": [fake.email() for _ in range(num_rows)],
    "Idade": np.random.randint(18, 70, num_rows),
    "Gênero": np.random.choice(["Masculino", "Feminino"], num_rows),
    "Cidade": [fake.city() for _ in range(num_rows)],
    "País": [fake.country() for _ in range(num_rows)],
    "Categoria_NPS": np.random.choice(["Detrator", "Neutro", "Promotor"], num_rows, p=[0.2, 0.4, 0.4]),
    "Comentário_Produto": [fake.sentence() for _ in range(num_rows)],
    "Comentário_Atendimento": [fake.sentence() for _ in range(num_rows)],
    "Comentário_Preço": [fake.sentence() for _ in range(num_rows)],
    "Comentário_Entrega": [fake.sentence() for _ in range(num_rows)],
    "Comentário_Geral": [fake.paragraph() for _ in range(num_rows)],
    "Data_Resposta": [fake.date_this_year() for _ in range(num_rows)]
}

# Criar DataFrame
df_nps = pd.DataFrame(data)

# Exibir as primeiras linhas
df_nps.head()

,ID_Cliente,Nome,Email,Idade,Gênero,Cidade,País,Categoria_NPS,Comentário_Produto,Comentário_Atendimento,Comentário_Preço,Comentário_Entrega,Comentário_Geral,Data_Resposta
0,1,Valerie Matthews,smithcaroline@example.com,24,Feminino,East Lindaborough,Turkmenistan,Detrator,Especially eat know activity.,Sport could office would themselves green.,Blue technology series image suffer military p...,Will life bit decision.,Military street girl hand painting minute thou...,2025-01-06
1,2,Heidi Douglas,elizabeth74@example.com,18,Masculino,Goodmanchester,Honduras,Promotor,Pressure quickly however gun field be.,Suffer information cover already phone father.,Huge spring big expert.,Doctor front decide wind should think night.,Itself share floor foot him require. Stand hos...,2025-01-29
2,3,Nicole Mata MD,irodriguez@example.net,55,Feminino,Erinborough,Oman,Detrator,Tell wind scientist.,Beyond throw likely speak.,Art enter front you.,Fast up before another firm fact.,Enter board dream his ever professor. Very I T...,2025-01-19
3,4,Brent Wise,jacksonmark@example.com,21,Masculino,Lake Kristaside,Heard Island and McDonald Islands,Neutro,Organization camera do find.,Instead travel mind data.,Safe suddenly really house big hotel.,Watch very matter so home my out.,Even street grow young never.,2025-01-14
4,5,Brianna Martin,btaylor@example.com,65,Masculino,Thompsonton,Iceland,Promotor,Respond product carry knowledge away.,Technology force front west.,Resource firm forget no south.,Us including heavy believe full face successful.,Worry already mention network. Short education...,2025-02-08